id: 2076ce7c7dad4bc4986f2393e29d8c46
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_283-The_Sutra_of_the_Three_Bodies-v1
  language: bo
  author: ''
  volume: {}
